name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.2
homepage: https://github.com/ash80/firebase_image

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  sqflite: ^2.2.6
  path: ^1.8.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
