name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.2
homepage: https://github.com/ash80/firebase_image

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  sqflite: ^2.2.3
  path: ^1.8.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
